version: 2

jobs:
  checkout_code:
    working_directory: ~/{{project_name}}
    docker:
      - image: circleci/python:3.6-stretch-node-browsers # remeber to update those!
    steps:
      - checkout
      - save_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/{{project_name}}
  build_dependencies_backend:
    working_directory: ~/{{project_name}}
    docker:
      - image: circleci/python:3.6-stretch-node-browsers # remeber to update those!
        environment:
          PIPENV_IGNORE_VIRTUALENVS: True
          PIPENV_VENV_IN_PROJECT: True
          PIPENV_DONT_LOAD_ENV: 0
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Environment.CIRCLE_SHA1 }}
      # this updates git-lfs to make pre-commit large files check hook work properly
      # more details in https://github.com/pre-commit/pre-commit-hooks/issues/252
      - run: curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
      - run: sudo apt-get install git-lfs --upgrade
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run: pip install requests pipenv --upgrade
      - restore_cache:
          keys:
            - pipenv-cache-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - run: pipenv install --dev
      - save_cache:
          key: pipenv-cache-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - .venv
            - /usr/local/bin
            - /usr/local/lib/python3.6/site-packages
  build_dependencies_frontend:
    working_directory: ~/{{project_name}}
    docker:
      - image: circleci/python:3.6-stretch-node-browsers # remeber to update those!
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - npm-cache-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - run: npm install
      - save_cache:
          key: npm-cache-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - node_modules
  run_test_lint_and_check_build_frontend:
    working_directory: ~/{{project_name}}
    docker:
      - image: circleci/python:3.6-stretch-node-browsers # remeber to update those!
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - npm-cache-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - run: npm run test
      - run: npm run lint
      - run: npm run build
  run_linters_and_test_backend:
    working_directory: ~/{{project_name}}
    docker:
      - image: circleci/python:3.6-stretch-node-browsers # remeber to update those!
        environment:
          PIPENV_IGNORE_VIRTUALENVS: True
          PIPENV_VENV_IN_PROJECT: True
          PIPENV_DONT_LOAD_ENV: 0
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Environment.CIRCLE_SHA1 }}
      # this updates git-lfs to make pre-commit large files check hook work properly
      # more details in https://github.com/pre-commit/pre-commit-hooks/issues/252
      - run: curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
      - run: sudo apt-get install git-lfs --upgrade
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          keys:
            - pipenv-cache-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      # style check
      - run: pipenv run prospector --messages-only
      # security checks
      - run: pipenv run bandit -r .
      - run: pipenv check
      # imports check
      - run: pipenv run isort **/*.py --check-only
      - run:
          command: pipenv run pre-commit run --all-files
          environment:
            SKIP: prospector,isort,eslint,missing-migrations
      - run:
          command: pipenv run python manage.py has_missing_migrations --ignore authtools
          environment:
            DJANGO_SETTINGS_MODULE: '{{project_name}}.settings.local_base'
      - run:
          command: pipenv run python manage.py check --deploy
          environment:
            DJANGO_SETTINGS_MODULE: '{{project_name}}.settings.production'
            SECRET_KEY: "$(python -c 'import uuid; print(uuid.uuid4().hex + uuid.uuid4().hex)')"
            DATABASE_URL: 'sqlite:///'
            ALLOWED_HOSTS: '.example.org'
            SENDGRID_USERNAME: 'test'
            SENDGRID_PASSWORD: 'test'
            REDIS_URL: 'redis://'
      - run: pipenv run coverage run manage.py test
      - run:
          command: |
            mkdir -p test-reports/
            pipenv run coverage xml -O test-reports/results.xml
          when: always
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports


workflows:
  version: 2
  build-workflow:
    jobs:
      - checkout_code:
          # This is necessary for the boilerplate's CI. You can remove these lines
          filters:
            branches:
              ignore: boilerplate-release
      - build_dependencies_backend:
          requires:
            - checkout_code
      - build_dependencies_frontend:
          requires:
            - checkout_code
      - run_test_lint_and_check_build_frontend:
          requires:
            - build_dependencies_frontend
      - run_linters_and_test_backend:
          requires:
            - build_dependencies_backend
              
